name: Publish to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Publish to GitHub Packages
      run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        signingKey: ${{ secrets.SIGNING_KEY }}
        signingPassword: ${{ secrets.SIGNING_PASSWORD }}
    
    - name: Publish to Maven Central
      if: github.event_name == 'release'
      run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
      env:
        centralUsername: ${{ secrets.CENTRAL_USERNAME }}
        centralPassword: ${{ secrets.CENTRAL_PASSWORD }}
        signingKey: ${{ secrets.SIGNING_KEY }}
        signingPassword: ${{ secrets.SIGNING_PASSWORD }}